version: '3'

volumes:
  jenkins_data:

services:
  keycloak:
    build:
      context: .
      dockerfile: keycloak-dockerfile
    image: jboss/keycloak
    container_name: keycloak
    ports:
      - "10001:8080"
    environment:
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    user: root

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    user: root
    ports:
      - "10000:8080"
    volumes:
      - jenkins_data/:/var/jenkins_home
